name: langis_mate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

  # Upgrade to Supabase v2.9.x, which uses sign_in_with_apple >=6.0.0
  supabase_flutter: ^2.9.0

  # Latest V2-embedding FlutterToast
  fluttertoast: ^8.2.12

  # (Optional) if you need to reference it directly
  sign_in_with_apple: ^6.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/langismate_logo.png
    - assets/images/slide1_welcome_to_langismate.png
    - assets/images/slide2_find_nearby_shops.png
    - assets/images/slide3_set_maintenance_reminders.png
